06 get reviews id comments
MikeDobinson/nc-portfolio-project-games pull request #7
Opened 2023-03-29 11:25 UTC by MikeDobinson

not fully happy with error handling. GET api/reviews/999/comments will return comments not found, NOT no review by that ID

2023-03-29 11:30 UTC, roisinoreilly requested changes
great job so far! There's just a few more tests I'd like you to implement, a valid id with no comments (a 200), an invalid id (eg. /not-an-id/comments) and a valid but non existent id (eg. /9999/comments). After you've added those send us another PR :)

2023-03-29 11:30 UTC, roisinoreilly commented on __tests__/app.test.js
> +                review_id: expect.any(Number),
we know that the review id should be 2 here not any number

2023-03-29 11:30 UTC, roisinoreilly commented on __tests__/app.test.js
> +          .expect(404)
this is actually a 200, it's a valid request to a valid endpoint, it should instead return an empty array of comments

2023-03-30 12:42 UTC, alexdevdavis approved these changes
Nicely done! Happy to approve this 👍

2023-03-30 12:48 UTC, merged